FROM python:2-alpine

RUN apk update

RUN apk add git build-base

RUN git clone https://github.com/poorna-kumar/gendermeme-core.git /gendermeme

WORKDIR /gendermeme

RUN pip install --upgrade pip

RUN pip install --no-cache-dir pycorenlp numpy

RUN apk --purge -v del git build-base

CMD ["python2"]
